Retailers/Goods/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from Goods import views

urlpatterns = [


    # 地址管理
    url(r'^address/$',views.address,name='address'),
    # 模板
    url(r'^frame/$',views.frame,name='frame'),
    # 账单
    url(r'^bill/$',views.bill,name='bill'),
    # 账单明细
    url(r'^billlist/$',views.billlist,name='billlist'),
    # 绑定手机
    url(r'^bindphone/$',views.bindphone,name='bindphone'),
    #新闻页面
    url(r'^blog/$',views.blog,name='blog'),
    #我的红包
    url(r'^bonus/$',views.bonus,name='bonus'),
    # 我的银行卡
    url(r'^cardlist/$', views.cardlist, name='cardlist'),
    # 银行卡绑定
    url(r'^cardmethod/$', views.cardmethod, name='cardmethod'),
    # 退换货管理
    url(r'^change/$', views.change, name='change'),
    # 我的收藏
    url(r'^collection/$', views.collection, name='collection'),
    # 评价管理
    url(r'^comment/$', views.comment, name='comment'),
    # 发表评论
    url(r'^commentlist/$', views.commentlist, name='commentlist'),
    url(r'^commentlist/(\d+)$', views.commentlist, name='commentlist1'),
    # 商品咨询
    url(r'^consultation/$', views.consultation, name='consultation'),
    # 优惠券
    url(r'^coupon/$', views.coupon, name='coupon'),
    # 邮箱验证
    url(r'^email/$', views.email, name='email'),
    # 我的足迹
    url(r'^foot/$', views.foot, name='foot'),
    # 实名认证
    url(r'^idcard/$', views.idcard, name='idcard'),
    # 个人中心
    url(r'^index/$', views.index, name='index'),
    # 个人资料
    url(r'^information/$', views.information, name='information'),
    # 物流信息
    url(r'^logistics/$', views.logistics, name='logistics'),
    # 我的消息
    url(r'^news/$', views.news, name='news'),
    # 订单管理
    url(r'^order/$', views.order, name='order'),
    # 订单详情
    url(r'^orderinfo/$', views.orderinfo, name='orderinfo'),
    url(r'^orderinfo/(\d+)$', views.orderinfo, name='orderinfo1'),
    # 修改密码
    url(r'^password/$', views.password, name='password'),
    # 我的积分
    url(r'^pointnew/$', views.pointnew, name='pointnew'),
    # 积分明细
    url(r'^points/$', views.points, name='points'),
    # 安全问题
    url(r'^question/$', views.question, name='question'),
    # 钱款去向
    url(r'^record/$', views.record, name='record'),
    # 退换货
    url(r'^refund/$', views.refund, name='refund'),
    url(r'^refund/(\d+)$', views.refund, name='refund1'),
    # 安全设置
    url(r'^safety/$', views.safety, name='safety'),
    # 支付密码
    url(r'^setpay/$', views.setpay, name='setpay'),
    # 意见反馈
    url(r'^suggest/$', views.suggest, name='suggest'),
    # 账户余额
    url(r'^wallet/$', views.wallet, name='wallet'),
    # 账户明细
    url(r'^walletlist/$', views.walletlist, name='walletlist'),
    # 登录页面
    url(r'^login/$', views.login, name='login'),
    # 获取注册验证码
    url(r'^auth_code_/$',views.auth_code_,name='auth_code_'),
    # 获取修改密码验证码
    url(r'^pswordcode_/$',views.pswordcode_,name='pswordcode_'),
    # 注册页面
    url(r'^register/$',views.register,name='register'),
    #删除session
    url(r'^sc/$',views.sc,name='sc'),
    #搜索路由
    url(r'^search/(\d+)/$',views.search,name='search1'),
    url(r'^search/$',views.search,name='search')

]

Retailers/Order/urls.py
from django.conf.urls import url, include
from Order import views

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^home/$', views.home,name='home'),
    url(r'^intro/(?P<goodid>\d+)/$',views.intro,name='intro'),
    # url(r'^purchase/$',views.purchase,name='purchase'),
    url(r'^price$',views.price_change,name='price'),
    url(r'^add_cart$',views.add_cart,name='add_cart'),
    url(r'^pay/(?P<commodityid>\d+)/(?P<count>\d+)/$',views.pay,name='pay'),
    url(r'^addre/$',views.addre,name='addre'),
    url(r'^express/$',views.express,name='express'),
    url(r'^commit/$',views.commit,name='commit'),
    url(r'^cart_commit/$', views.cart_commit, name='cart_commit'),
    url(r'^shopcart/$',views.shopcart,name='shopcart'),
    url(r'^check_cart$', views.check_cart, name='check_cart'),
    url(r'^delete_cart$', views.delete_cart, name='delete_cart'),
    url(r'^cart_pay/$', views.cart_pay, name='cart_pay'),
    url(r'^order_pay/$', views.order_pay, name='order_pay')
]

Retailers/Retailers/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),

    url(r'^goods/', include('Goods.urls', namespace='goods')),

    url(r'^order/', include('Order.urls', namespace='order')),

    url(r'^admin/', include('User.urls', namespace='admin'))
]

Retailers/User/urls.py
from django.conf.urls import url


from User import views
# from User.views import OrderPayView

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^add/$', views.add, name='add'),
    url(r'^login/$', views.login, name='login'),
    url(r'^index/$', views.index, name='index'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^productlist/(\d+)/$', views.productlist, name='productlist1'),
    url(r'^productlist/$', views.productlist, name='productlist'),
    url(r'^addgood/$', views.addgood, name='addgood'),
    url(r'^altergood/$', views.altergood, name='altergood'),
    url(r'^delgood/$', views.delgood, name='delgood'),
    url(r'^addband/$', views.addband, name='addband'),
    url(r'^alterband/$', views.alterband, name='alterband'),
    url(r'^delband/$', views.delband, name='delband'),
    url(r'^addbigcategory/$', views.addbigcategory, name='addbigcategory'),
    url(r'^alterbigcategory/$', views.alterbigcategory, name='alterbigcategory'),
    url(r'^delbigcategory/$', views.delbigcategory, name='delbigcategory'),
    url(r'^addsmallcategory/$', views.addsmallcategory, name='addsmallcategory'),
    url(r'^altersmallcategory/$', views.altersmallcategory, name='altersmallcategory'),
    url(r'^delsmallcategory/$', views.delsmallcategory, name='delsmallcategory'),
    url(r'^addattrbute/$', views.addattrbute, name='addattrbute'),
    url(r'^alterattrbute/$', views.alterattrbute, name='alterattrbute'),
    url(r'^delattrbute/$', views.delattrbute, name='delattrbute'),
    url(r'^addinventory/$', views.addinventory, name='addinventory'),
    url(r'^addinventory1/$', views.addinventory1, name='addinventory1'),
    url(r'^addinventory2/$', views.addinventory2, name='addinventory2'),
    url(r'^addinventory3/$', views.addinventory3, name='addinventory3'),
    url(r'^addinventory4/$', views.addinventory4, name='addinventory4'),
    url(r'^addgoodetail/$', views.addgoodetail, name='addgoodetail'),
    url(r'^orderlist/$', views.orderlist, name='orderlist'),
    url(r'^orderlist/(\d+)$', views.orderlist, name='orderlist1'),
    url(r'^choiceorder/(\d+)$', views.choiceorder, name='choiceorder1'),
    url(r'^choiceorder/$', views.choiceorder, name='choiceorder'),
    url(r'^delorder/(\d+)/$', views.delorder, name='delorder'),
    url(r'^orderdetail/(\d+)/$', views.orderdetail, name='orderdetail'),
    url(r'^sendorder/(\d+)/$', views.sendorder, name='sendorder'),
    url(r'^userlist/(\d+)/$', views.userlist, name='userlist1'),
    url(r'^userlist/$', views.userlist, name='userlist'),
    url(r'^deluser/(\d+)/$', views.deluser, name='deluser'),
    url(r'^userdetail/(\d+)/$', views.userdetail, name='userdetail'),
    url(r'^userrank/$', views.userrank, name='userrank'),
    url(r'^useraccount/$', views.useraccount, name='useraccount'),
    url(r'^setting/$', views.setting, name='setting'),
    url(r'^expresslist/$', views.expresslist, name='expresslist'),
    url(r'^delexpress/(\d)/$', views.delexpress, name='delexpress'),
    url(r'^paylist/$', views.paylist, name='paylist'),
    url(r'^delpayway/(\d)/$', views.delpayway, name='delpayway'),
    url(r'^pageviews/$', views.pageviews, name='pageviews'),
    url(r'^sales/$', views.sales, name='sales'),
    url(r"^pay/$", views.pay, name='pay'),
    url(r'^checkpay/$', views.checkpay, name='checkpay'),
    url(r'^test/$', views.test, name='test'),
    url(r'^turn/$', views.turn, name='turn')

]

Retailers/templates/shop/child.html
{% extends  'shop/frame.html' %}
{% load static %}
{% block head %}
    <link href="{% static  '/shop/AmazeUI-2.4.2/assets/css/admin.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static  '/shop/AmazeUI-2.4.2/assets/css/amazeui.css' %}" rel="stylesheet" type="text/css">

    <link href="{% static  '/shop/css/personal.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static  '/shop/css/addstyle.css' %}" rel="stylesheet" type="text/css">
    <script src="{% static  '/shop/AmazeUI-2.4.2/assets/js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static  '/shop/AmazeUI-2.4.2/assets/js/amazeui.js' %}" type="text/javascript"></script>
{% endblock %}
{% block change %}
    <div class="am-cf am-padding">
        <div class="am-fl am-cf"><strong class="am-text-danger am-text-lg">订单aaaaaaaaaaa管理</strong> /
            <small>Order</small>
        </div>
    </div>
{% endblock %}
{% block blank %}

    <ul class="am-avg-sm-1 am-avg-md-3 am-thumbnails">

        <li class="user-addresslist defaultAddr">
            <span class="new-option-r"><i class="am-icon-check-circle"></i>默认地址</span>
            <p class="new-tit new-p-re">
                <span class="new-txt">小叮当</span>
                <span class="new-txt-rd2">159****1622</span>
            </p>
            <div class="new-mu_l2a new-p-re">
                <p class="new-mu_l2cw">
                    <span class="title">地址：</span>
                    <span class="province">湖北</span>省
                    <span class="city">武汉</span>市
                    <span class="dist">洪山</span>区
                    <span class="street">雄楚大道666号(中南财经政法大学)</span></p>
            </div>
            <div class="new-addr-btn">
                <a href="#"><i class="am-icon-edit"></i>编辑</a>
                <span class="new-addr-bar">|</span>
                <a href="javascript:void(0);" onclick="delClick(this);"><i class="am-icon-trash"></i>删除</a>
            </div>
        </li>

        <li class="user-addresslist">
            <span class="new-option-r"><i class="am-icon-check-circle"></i>设为默认</span>
            <p class="new-tit new-p-re">
                <span class="new-txt">小叮当</span>
                <span class="new-txt-rd2">159****1622</span>
            </p>
            <div class="new-mu_l2a new-p-re">
                <p class="new-mu_l2cw">
                    <span class="title">地址：</span>
                    <span class="province">湖北</span>省
                    <span class="city">武汉</span>市
                    <span class="dist">洪山</span>区
                    <span class="street">雄楚大道666号(中南财经政法大学)</span></p>
            </div>
            <div class="new-addr-btn">
                <a href="#"><i class="am-icon-edit"></i>编辑</a>
                <span class="new-addr-bar">|</span>
                <a href="javascript:void(0);" onclick="delClick(this);"><i class="am-icon-trash"></i>删除</a>
            </div>
        </li>
        <li class="user-addresslist">
            <span class="new-option-r"><i class="am-icon-check-circle"></i>设为默认</span>
            <p class="new-tit new-p-re">
                <span class="new-txt">小叮当</span>
                <span class="new-txt-rd2">159****1622</span>
            </p>
            <div class="new-mu_l2a new-p-re">
                <p class="new-mu_l2cw">
                    <span class="title">地址：</span>
                    <span class="province">湖北</span>省
                    <span class="city">武汉</span>市
                    <span class="dist">洪山</span>区
                    <span class="street">雄楚大道666号(中南财经政法大学)</span></p>
            </div>
            <div class="new-addr-btn">
                <a href="#"><i class="am-icon-edit"></i>编辑</a>
                <span class="new-addr-bar">|</span>
                <a href="javascript:void(0);" onclick="delClick(this);"><i class="am-icon-trash"></i>删除</a>
            </div>
        </li>
    </ul>
    <div class="clear"></div>
    <a class="new-abtn-type" data-am-modal="{target: '#doc-modal-1', closeViaDimmer: 0}">添加新地址</a>
    <!--例子-->
    <div class="am-modal am-modal-no-btn" id="doc-modal-1">

        <div class="add-dress">

            <!--标题 -->
            <div class="am-cf am-padding">
                <div class="am-fl am-cf"><strong class="am-text-danger am-text-lg">新增地址</strong> /
                    <small>Add&nbsp;address</small>
                </div>
            </div>
            <hr/>

            <div class="am-u-md-12 am-u-lg-8" style="margin-top: 20px;">
                <form class="am-form am-form-horizontal">

                    <div class="am-form-group">
                        <label for="user-name" class="am-form-label">收货人</label>
                        <div class="am-form-content">
                            <input type="text" id="user-name" placeholder="收货人">
                        </div>
                    </div>

                    <div class="am-form-group">
                        <label for="user-phone" class="am-form-label">手机号码</label>
                        <div class="am-form-content">
                            <input id="user-phone" placeholder="手机号必填" type="email">
                        </div>
                    </div>
                    <div class="am-form-group">
                        <label for="user-address" class="am-form-label">所在地</label>
                        <div class="am-form-content address">
                            <select data-am-selected>
                                <option value="a">浙江省</option>
                                <option value="b" selected>湖北省</option>
                            </select>
                            <select data-am-selected>
                                <option value="a">温州市</option>
                                <option value="b" selected>武汉市</option>
                            </select>
                            <select data-am-selected>
                                <option value="a">瑞安区</option>
                                <option value="b" selected>洪山区</option>
                            </select>
                        </div>
                    </div>

                    <div class="am-form-group">
                        <label for="user-intro" class="am-form-label">详细地址</label>
                        <div class="am-form-content">
                            <textarea class="" rows="3" id="user-intro" placeholder="输入详细地址"></textarea>
                            <small>100字以内写出你的详细地址...</small>
                        </div>
                    </div>

                    <div class="am-form-group">
                        <div class="am-u-sm-9 am-u-sm-push-3">
                            <a class="am-btn am-btn-danger">保存</a>
                            <a href="javascript: void(0)" class="am-close am-btn am-btn-danger"
                               data-am-modal-close>取消</a>
                        </div>
                    </div>
                </form>
            </div>

        </div>

    </div>

    </div>

    <script type="text/javascript">
        $(document).ready(function () {
            $(".new-option-r").click(function () {
                $(this).parent('.user-addresslist').addClass("defaultAddr").siblings().removeClass("defaultAddr");
            });

            var $ww = $(window).width();
            if ($ww > 640) {
                $("#doc-modal-1").removeClass("am-modal am-modal-no-btn")
            }

        })
    </script>

    <div class="clear"></div>

    </div>

{% endblock %}

Retailers/templates/shop/frame.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    {% block meta %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0,maximum-scale=1.0, user-scalable=0">
    {% endblock %}
    {% block title %}

    {% endblock %}
    {% block head %}

    {% endblock %}
</head>


<body>
<!--头 -->
<header>
    <article>
        <div class="mt-logo">
            <!--顶部导航条 -->
            <div class="am-container header">
                <ul class="message-l">
                    <div class="topMessage">
                        <div class="menu-hd">
                            {% if  'username' in request.session or 'email' in request.session or 'phone' in request.session  %}
                              欢迎
                                {% if request.session.username %}
                                    {{ request.session.username }}
                                {% elif request.session.email %}
                                    {{ request.session.email }}
                                {% elif request.session.phone %}
                                    {{ request.session.phone }}
                                {% endif %}
                                <a href="{% url 'goods:sc' %}" target="_top" class="h">退出</a>

                            {% else %}
                               <a href="{% url 'goods:login' %}" target="_top" class="h">亲，请登录</a>
                                <a href="{% url 'goods:register' %}" target="_top">免费注册</a>

                            {% endif %}
                        </div>
                    </div>

                </ul>
                <ul class="message-r">
                    <div class="topMessage home">
                        <div class="menu-hd"><a href="{% url 'order:home' %}" target="_top" class="h">商城首页</a></div>
                    </div>
                    <div class="topMessage my-shangcheng">
                        <div class="menu-hd MyShangcheng"><a href="{% url 'goods:index' %}" target="_top"><i
                                class="am-icon-user am-icon-fw"></i>个人中心</a></div>
                    </div>
                    <div class="topMessage mini-cart">
                        <div class="menu-hd"><a id="mc-menu-hd" href="#" target="_top"><i
                                class="am-icon-shopping-cart  am-icon-fw"></i><span>购物车</span><strong id="J_MiniCartNum"
                                                                                                      class="h">0</strong></a>
                        </div>
                    </div>
                    <div class="topMessage favorite">
                        <div class="menu-hd"><a href="#" target="_top"><i
                                class="am-icon-heart am-icon-fw"></i><span>收藏夹</span></a></div>
                    </div>
                </ul>

            </div>

            <!--悬浮搜索框-->

            <div class="nav white">
                <div class="logoBig">
                    <li><img src="{% static 'shop/images/logobig.png' %}"/></li>
                </div>

                <div class="search-bar pr">
{#                    <a name="index_none_header_sysc" href="#"></a>#}
                    <form action="{% url 'goods:search' %}" method="post">
                        {% csrf_token %}
                        <input id="searchInput" name="index_none_header_sysc" type="text" placeholder="搜索" autocomplete="off">
                        <input id="ai-topsearch" class="submit am-btn" value="搜索" index="1" type="submit">
                    </form>
                </div>
            </div>

            <div class="clear"></div>
        </div>

    </article>
</header>

<div class="nav-table">
    <div class="long-title"><span class="all-goods">全部分类</span></div>
    <div class="nav-cont">
        <ul>
            <li class="index"><a href="#">首页</a></li>
            <li class="qc"><a href="#">闪购</a></li>
            <li class="qc"><a href="#">限时抢</a></li>
            <li class="qc"><a href="#">团购</a></li>
            <li class="qc last"><a href="#">大包装</a></li>
        </ul>

    </div>
</div>
<b class="line"></b>

{% block blog %}

    <div class="center">
        <div class="col-main">
            <div class="main-wrap">
                {% block content %}

                {% endblock %}
            </div>
            {% block footer %}
                <!--底部-->
                <div class="footer">
                    <div class="footer-hd">
                        <p>
                            <a href="#">恒望科技</a>
                            <b>|</b>
                            <a href="#">商城首页</a>
                            <b>|</b>
                            <a href="#">支付宝</a>
                            <b>|</b>
                            <a href="#">物流</a>
                        </p>
                    </div>
                    <div class="footer-bd">
                        <p>
                            <a href="#">关于恒望</a>
                            <a href="#">合作伙伴</a>
                            <a href="#">联系我们</a>
                            <a href="#">网站地图</a>
                            <em>© 2015-2025 Hengwang.com 版权所有</em>
                        </p>
                    </div>
                </div>
            {% endblock %}
        </div>

        <aside class="menu">
            <ul>
                <li class="person active">
                    <a href="{% url 'goods:index' %}"><i class="am-icon-user"></i>个人中心</a>
                </li>
                <li class="person">
                    <p><i class="am-icon-newspaper-o"></i>个人资料</p>
                    <ul>
                        <li><a href="{% url 'goods:information' %}">个人信息</a></li>
                        <li><a href="{% url 'goods:safety' %}">安全设置</a></li>
                        <li><a href="{% url 'goods:address' %}">地址管理</a></li>
{#                        <li><a href="{% url 'goods:cardlist' %}">快捷支付</a></li>#}
                    </ul>
                </li>
                <li class="person">
                    <p><i class="am-icon-balance-scale"></i>我的交易</p>
                    <ul>
                        <li><a href="{% url 'goods:order' %}">订单管理</a></li>
                        <li><a href="{% url 'goods:change' %}">退款售后</a></li>
                        <li><a href="{% url 'goods:comment' %}">评价商品</a></li>
{#                        <li><a href="{% url 'goods:refund' %}">退换货申请</a></li>#}
                    </ul>
                </li>
                <li class="person">
                    <p><i class="am-icon-dollar"></i>我的资产</p>
                    <ul>
                        <li><a href="{% url 'goods:points' %}">我的积分</a></li>
{#                        <li><a href="{% url 'goods:coupon' %}">优惠券 </a></li>#}
{#                        <li><a href="{% url 'goods:bonus' %}">红包</a></li>#}
{#                        <li><a href="{% url 'goods:walletlist' %}">账户余额</a></li>#}
{#                        <li><a href="{% url 'goods:bill' %}">账单明细</a></li>#}
                    </ul>
                </li>

{#                <li class="person">#}
{#                    <p><i class="am-icon-tags"></i>我的收藏</p>#}
{#                    <ul>#}
{#                        <li><a href="{% url 'goods:collection' %}">收藏</a></li>#}
{#                        <li><a href="{% url 'goods:foot' %}">足迹</a></li>#}
{#                    </ul>#}
{#                </li>#}

{#                <li class="person">#}
{#                    <p><i class="am-icon-qq"></i>在线客服</p>#}
{#                    <ul>#}
{#                        <li><a href="{% url 'goods:consultation' %}">商品咨询</a></li>#}
{#                        <li><a href="{% url 'goods:suggest' %}">意见反馈</a></li>#}
{##}
{#                        <li><a href="{% url 'goods:news' %}">我的消息</a></li>#}
{#                    </ul>#}
{#                </li>#}
            </ul>

        </aside>
    </div>
{% endblock %}
</body>

</html>