Retailers/Goods/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from Goods import views

urlpatterns = [


    # 地址管理
    url(r'^address/$',views.address,name='address'),
    # 模板
    url(r'^frame/$',views.frame,name='frame'),
    # 账单
    url(r'^bill/$',views.bill,name='bill'),
    # 账单明细
    url(r'^billlist/$',views.billlist,name='billlist'),
    # 绑定手机
    url(r'^bindphone/$',views.bindphone,name='bindphone'),
    #新闻页面
    url(r'^blog/$',views.blog,name='blog'),
    #我的红包
    url(r'^bonus/$',views.bonus,name='bonus'),
    # 我的银行卡
    url(r'^cardlist/$', views.cardlist, name='cardlist'),
    # 银行卡绑定
    url(r'^cardmethod/$', views.cardmethod, name='cardmethod'),
    # 退换货管理
    url(r'^change/$', views.change, name='change'),
    # 我的收藏
    url(r'^collection/$', views.collection, name='collection'),
    # 评价管理
    url(r'^comment/$', views.comment, name='comment'),
    # 发表评论
    url(r'^commentlist/$', views.commentlist, name='commentlist'),
    url(r'^commentlist/(\d+)$', views.commentlist, name='commentlist1'),
    # 商品咨询
    url(r'^consultation/$', views.consultation, name='consultation'),
    # 优惠券
    url(r'^coupon/$', views.coupon, name='coupon'),
    # 邮箱验证
    url(r'^email/$', views.email, name='email'),
    # 我的足迹
    url(r'^foot/$', views.foot, name='foot'),
    # 实名认证
    url(r'^idcard/$', views.idcard, name='idcard'),
    # 个人中心
    url(r'^index/$', views.index, name='index'),
    # 个人资料
    url(r'^information/$', views.information, name='information'),
    # 物流信息
    url(r'^logistics/$', views.logistics, name='logistics'),
    # 我的消息
    url(r'^news/$', views.news, name='news'),
    # 订单管理
    url(r'^order/$', views.order, name='order'),
    # 订单详情
    url(r'^orderinfo/$', views.orderinfo, name='orderinfo'),
    url(r'^orderinfo/(\d+)$', views.orderinfo, name='orderinfo1'),
    # 修改密码
    url(r'^password/$', views.password, name='password'),
    # 我的积分
    url(r'^pointnew/$', views.pointnew, name='pointnew'),
    # 积分明细
    url(r'^points/$', views.points, name='points'),
    # 安全问题
    url(r'^question/$', views.question, name='question'),
    # 钱款去向
    url(r'^record/$', views.record, name='record'),
    # 退换货
    url(r'^refund/$', views.refund, name='refund'),
    url(r'^refund/(\d+)$', views.refund, name='refund1'),
    # 安全设置
    url(r'^safety/$', views.safety, name='safety'),
    # 支付密码
    url(r'^setpay/$', views.setpay, name='setpay'),
    # 意见反馈
    url(r'^suggest/$', views.suggest, name='suggest'),
    # 账户余额
    url(r'^wallet/$', views.wallet, name='wallet'),
    # 账户明细
    url(r'^walletlist/$', views.walletlist, name='walletlist'),
    # 登录页面
    url(r'^login/$', views.login, name='login'),
    # 获取注册验证码
    url(r'^auth_code_/$',views.auth_code_,name='auth_code_'),
    # 获取修改密码验证码
    url(r'^pswordcode_/$',views.pswordcode_,name='pswordcode_'),
    # 注册页面
    url(r'^register/$',views.register,name='register'),
    #删除session
    url(r'^sc/$',views.sc,name='sc'),
    #搜索路由
    url(r'^search/(\d+)/$',views.search,name='search1'),
    url(r'^search/$',views.search,name='search')

]

Retailers/Order/urls.py
from django.conf.urls import url, include
from Order import views

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^home/$', views.home,name='home'),
    url(r'^intro/(?P<goodid>\d+)/$',views.intro,name='intro'),
    # url(r'^purchase/$',views.purchase,name='purchase'),
    url(r'^price$',views.price_change,name='price'),
    url(r'^add_cart$',views.add_cart,name='add_cart'),
    url(r'^pay/(?P<commodityid>\d+)/(?P<count>\d+)/$',views.pay,name='pay'),
    url(r'^addre/$',views.addre,name='addre'),
    url(r'^express/$',views.express,name='express'),
    url(r'^commit/$',views.commit,name='commit'),
    url(r'^cart_commit/$', views.cart_commit, name='cart_commit'),
    url(r'^shopcart/$',views.shopcart,name='shopcart'),
    url(r'^check_cart$', views.check_cart, name='check_cart'),
    url(r'^delete_cart$', views.delete_cart, name='delete_cart'),
    url(r'^cart_pay/$', views.cart_pay, name='cart_pay'),
    url(r'^order_pay/$', views.order_pay, name='order_pay')
]

Retailers/Retailers/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),

    url(r'^goods/', include('Goods.urls', namespace='goods')),

    url(r'^order/', include('Order.urls', namespace='order')),

    url(r'^admin/', include('User.urls', namespace='admin'))
]

Retailers/User/urls.py
from django.conf.urls import url


from User import views
# from User.views import OrderPayView

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^add/$', views.add, name='add'),
    url(r'^login/$', views.login, name='login'),
    url(r'^index/$', views.index, name='index'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^productlist/(\d+)/$', views.productlist, name='productlist1'),
    url(r'^productlist/$', views.productlist, name='productlist'),
    url(r'^addgood/$', views.addgood, name='addgood'),
    url(r'^altergood/$', views.altergood, name='altergood'),
    url(r'^delgood/$', views.delgood, name='delgood'),
    url(r'^addband/$', views.addband, name='addband'),
    url(r'^alterband/$', views.alterband, name='alterband'),
    url(r'^delband/$', views.delband, name='delband'),
    url(r'^addbigcategory/$', views.addbigcategory, name='addbigcategory'),
    url(r'^alterbigcategory/$', views.alterbigcategory, name='alterbigcategory'),
    url(r'^delbigcategory/$', views.delbigcategory, name='delbigcategory'),
    url(r'^addsmallcategory/$', views.addsmallcategory, name='addsmallcategory'),
    url(r'^altersmallcategory/$', views.altersmallcategory, name='altersmallcategory'),
    url(r'^delsmallcategory/$', views.delsmallcategory, name='delsmallcategory'),
    url(r'^addattrbute/$', views.addattrbute, name='addattrbute'),
    url(r'^alterattrbute/$', views.alterattrbute, name='alterattrbute'),
    url(r'^delattrbute/$', views.delattrbute, name='delattrbute'),
    url(r'^addinventory/$', views.addinventory, name='addinventory'),
    url(r'^addinventory1/$', views.addinventory1, name='addinventory1'),
    url(r'^addinventory2/$', views.addinventory2, name='addinventory2'),
    url(r'^addinventory3/$', views.addinventory3, name='addinventory3'),
    url(r'^addinventory4/$', views.addinventory4, name='addinventory4'),
    url(r'^addgoodetail/$', views.addgoodetail, name='addgoodetail'),
    url(r'^orderlist/$', views.orderlist, name='orderlist'),
    url(r'^orderlist/(\d+)$', views.orderlist, name='orderlist1'),
    url(r'^choiceorder/(\d+)$', views.choiceorder, name='choiceorder1'),
    url(r'^choiceorder/$', views.choiceorder, name='choiceorder'),
    url(r'^delorder/(\d+)/$', views.delorder, name='delorder'),
    url(r'^orderdetail/(\d+)/$', views.orderdetail, name='orderdetail'),
    url(r'^sendorder/(\d+)/$', views.sendorder, name='sendorder'),
    url(r'^userlist/(\d+)/$', views.userlist, name='userlist1'),
    url(r'^userlist/$', views.userlist, name='userlist'),
    url(r'^deluser/(\d+)/$', views.deluser, name='deluser'),
    url(r'^userdetail/(\d+)/$', views.userdetail, name='userdetail'),
    url(r'^userrank/$', views.userrank, name='userrank'),
    url(r'^useraccount/$', views.useraccount, name='useraccount'),
    url(r'^setting/$', views.setting, name='setting'),
    url(r'^expresslist/$', views.expresslist, name='expresslist'),
    url(r'^delexpress/(\d)/$', views.delexpress, name='delexpress'),
    url(r'^paylist/$', views.paylist, name='paylist'),
    url(r'^delpayway/(\d)/$', views.delpayway, name='delpayway'),
    url(r'^pageviews/$', views.pageviews, name='pageviews'),
    url(r'^sales/$', views.sales, name='sales'),
    url(r"^pay/$", views.pay, name='pay'),
    url(r'^checkpay/$', views.checkpay, name='checkpay'),
    url(r'^test/$', views.test, name='test'),
    url(r'^turn/$', views.turn, name='turn')

]

Retailers/Order/views.py
import os

from alipay import AliPay
from django.core.serializers import json
from django.db.models import Count, Sum
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.template import loader
from django.urls import reverse

from Goods.models import CommodityCategories, CommodityBrand, Goods, Goodsdetails, CommodityCategoriesTwo, Specification
from Retailers import settings
from User.models import User_address, Express_company

from .models import Mobilecount
from django.db import connection
# Create your views here.
from .models import *

def home(request):
    # # temp = loader.get_template('shop/home/home3.html')
    dlb = CommodityCategories.objects.filter(parentid=0)  # 寻找大类别 3
    xlb = CommodityCategories.objects.exclude(parentid=0)  # 寻找小类别 3
    store = CommodityBrand.objects.all()  # 寻找品牌 2
    price = CommodityCategoriesTwo.objects.all()
    dic = {}
    if request.session.get('username'):
        user = User.objects.get(username=request.session.get('username'))
        shop = ShopcartTwentyfour.objects.filter(uid=user.uid).count()
    else:
        shop = 0

    for lb in dlb:
        for xl in xlb:
            if xl.parentid == lb.id:
                print(xl.categoryname,'33333333')


    for i in dlb:
        list =[]
        list.clear()
        dic[i.id] = list
        commodity = CommodityCategories.objects.filter(parentid=i.id).values('id')
        for j in commodity:

            a = Goods.objects.filter(smallclassesid=j['id'])
            if len(a):
                for num in a:
                    list.append(num)

        list1=list[-6:]

        dic[i.id] = list

    return render(request,'shop/home/home3.html',context={'dlb': dlb,'shopnum':shop ,'xlb': xlb, 'store': store,'dic':dic,'price':price})
    # return HttpResponse(res)
    # return render(request,'shop/home/home3.html')




def intro(request,goodid):
    detail = Goodsdetails.objects.filter(Goodsid=goodid).first()#提供商品详情与展示图
    # print(goodid,'+++++++++++++++++++++++++++++++')
    goods = Goods.objects.filter(gid = goodid).first()#属性主表查商品详情，提供商品名称
    attr = CommodityCategoriesTwo.objects.filter(gid = goodid).first()#属性附表查详情 提供现在价格与历史价格
    # attrnum = CommodityCategoriesTwo.objects.filter(gid=goodid).values('gid').annotate(Count('smallclassesattribute'))
    # attrnum = CommodityCategoriesTwo.objects.filter(gid=goodid).values('smallclassesattribute').distinct().count()#提供小类别个数
    attrnum = CommodityCategoriesTwo.objects.filter(gid=goodid).values('smallclassesattribute').distinct()#提供小类别的详情
    norm = CommodityCategoriesTwo.objects.filter(gid=goodid).values('specification_id').distinct()#与当前商品相关的规格
    inven = CommodityCategoriesTwo.objects.get(gid=goodid,is_show=1)
    normall = Specification.objects.all()#所有规格
    print(norm[0]['specification_id'],normall[0].id)
    # temp = loader.get_template('shop/home/introduction.html')
    if request.session.get('username'):
        user = User.objects.get(username=request.session.get('username'))
        shop = ShopcartTwentyfour.objects.filter(uid=user.uid).count()
    else:
        shop = 0



    print("attrnum",attrnum)
    # res = temp.render(context={'detail': detail, 'inven':inven,'num':1,'goods': goods, 'attr': attr, 'attrnum': attrnum, 'norm': norm, 'normall': normall})
    return render(request,'shop/home/introduction.html',context={'detail': detail,'shopnum':shop, 'inven':inven,'num':1,'goods': goods, 'attr': attr, 'attrnum': attrnum, 'norm': norm, 'normall': normall})


# def purchase(request):
#     if request.method == "POST":
#         fenliang_value = request.POST.get("fenliang_value")
#         kouwei_value = request.POST.get("kouwei_value")
#         goodid = request.POST.get("goodid")
#         count = request.POST.get("count")
#
#         print('+++++++++++++++++++++++')
#         data = {
#
#
#         }
#         return JsonResponse(data)
#     return render(request,'shop/home/pay.html')


def price_change(request):
    if request.method == "POST":
        fenliang_value = request.POST.get("fenliang_value")
        kouwei_value = request.POST.get("kouwei_value")
        goodid = request.POST.get("goodid")
        norm = Specification.objects.get(specification=fenliang_value)

        count = request.POST.get("count")
        fenliang = Specification.objects.get(specification=fenliang_value)
        attr = CommodityCategoriesTwo.objects.get(gid=goodid, specification_id=fenliang.id,smallclassesattribute=kouwei_value)
        price = CommodityCategoriesTwo.objects.get(gid=goodid,smallclassesattribute=kouwei_value,specification_id=norm.id)

        if price:
            total_count = price.inventory

            data = {
                "total_price":price.price,
                "total_count":total_count,
                'goods': attr.id,
                'count': count
            }
            return JsonResponse(data)
        else:
            data = {
                "total_price": '',
                "total_count": 0,
                'goods': attr.id,
                'count': count
            }
            return JsonResponse(data)


def add_cart(request):
    if request.method == "POST":
        user =User.objects.get(username=request.session.get('username'))
        a=request.POST.get('updatanum')
        b=request.POST.get('commodityid')
        commodity = CommodityCategoriesTwo.objects.get(id = int(b))



        shop1 = ShopcartTwentyfour.objects.filter(cid=commodity.id,uid=user.uid).exists()
        if shop1:
            shop = ShopcartTwentyfour.objects.get(cid=commodity.id, uid=user.uid)
            shop.goodscount = shop.goodscount + int(a)
            shop.totalprice = shop.price*int(a)+shop.totalprice
            shop.save()
            num = ShopcartTwentyfour.objects.filter(uid=user.uid).count()
            data = {
            'num':num
            }
            return JsonResponse(data)
        else:

            myshopcart = ShopcartTwentyfour(uid=user.uid, goodscount=int(a), cid=commodity.id,price=commodity.price,totalprice=int(a)*int(commodity.price))
            myshopcart.save()
            num = ShopcartTwentyfour.objects.filter(uid=user.uid).count()
            data = {
            'num': num
            }
            return JsonResponse(data)
    # return render(request,'shop/home/introduction.html')


def pay(request,commodityid,count):
    userid = User.objects.get(username = request.session.get('username')).uid
    address = User_address.objects.filter(uid_id = userid)
    express = Express_company.objects.all()
    if request.session.get('username'):
        user = User.objects.get(username=request.session.get('username'))
        shop = ShopcartTwentyfour.objects.filter(uid=user.uid).count()
    else:
        shop = 0
    commodity = CommodityCategoriesTwo.objects.get(id=commodityid)
    goods = Goods.objects.get(gid=commodity.gid)
    norm = Specification.objects.get(id=commodity.specification_id)
    total_price = int(commodity.price)*int(count)
    total=total_price+10
    if request.method == 'POST':
        username = request.session.get('username')
        user = User.objects.filter(username=username)[0]
        uid = User.objects.filter(username=username)[0].uid
        address = user.user_address_set.all()
        # print(address)
        aid = request.GET.get('aid')
        dell = request.GET.get('del')
        if aid:
            # 取消原有默认地址
            userr = user.user_address_set.filter(default_address=1)[0]
            userr.default_address = 0
            userr.save()
            # 设置新的默认地址
            userr = user.user_address_set.filter(aid=aid)[0]
            userr.default_address = 1
            userr.save()
        if dell:
            useraddress = user.user_address_set.filter(pk=dell)
            useraddress.delete()
            return HttpResponse(json.dumps({'data': '删除成功'}), content_type='application/json')
        if request.method == "POST":
            user_name = request.POST.get('user-name')
            user_phone = request.POST.get('user-phone')
            cmbProvince = request.POST.get('cmbProvince')
            cmbCity = request.POST.get('cmbCity')
            cmbArea = request.POST.get('cmbArea')
            detail_address = request.POST.get('user-intro')
            location = cmbProvince + cmbCity + cmbArea
            print(user_name, user_phone, cmbProvince, cmbCity, cmbArea)
            User_address.objects.create(location=location, detail_address=detail_address, receiver=user_name,
                                        phone_number=user_phone, uid_id=uid)


    return render(request,'shop/home/pay.html',context={'shopnum':shop,'express':express,'address':address,'goods':goods,'commodity':commodity,'count':count,'norm':norm,'total_price':total_price,'total':total})


def addre(request):
    if request.method == 'POST':
        address = request.POST.get('address')
        myad = User_address.objects.get(aid = address)
        reciever = myad.receiver
        phone =myad.phone_number
        location = myad.location
        detail_info = myad.detail_address
        data = {
            'reciever':reciever,
            'phone':phone,
            'location':location,
            'info1':detail_info
        }
        return JsonResponse(data)
    # return render(request,'shop/home/pay.html')


def express(request):
    if request.method == 'POST':
        express_name= request.POST.get('express_name')
        price = request.POST.get('price')
        express = Express_company.objects.get(express_name = express_name)
        ex_id = express.id
        ex_money = express.express_price
        ex_name = express.express_name
        ex_price = int(price)+int(ex_money)
        data = {
            'ex_id':ex_id,
            'ex_money':ex_money,
            'ex_name':ex_name,
            'ex_price':ex_price
        }
        return JsonResponse(data)
    # return render(request, 'shop/home/pay.html')


def commit(request):

Retailers/templates/shop/person/billlist.html
{% extends 'shop/frame.html' %}
{% load static %}
{% block title %}
    <title>账单明细</title>
{% endblock %}
{% block head %}
        <link href="{% static 'shop/AmazeUI-2.4.2/assets/css/admin.css' %}" rel="stylesheet" type="text/css"/>
        <link href="{% static 'shop/AmazeUI-2.4.2/assets/css/amazeui.css' %}" rel="stylesheet" type="text/css"/>
        <link href="{% static 'shop/css/personal.css' %}" rel="stylesheet" type="text/css"/>
        <link href="{% static 'shop/css/blstyle.css' %}" rel="stylesheet" type="text/css"/>
        <script src="{% static 'shop/AmazeUI-2.4.2/assets/js/jquery.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'shop/AmazeUI-2.4.2/assets/js/amazeui.js' %}" type="text/javascript"></script>



{#		<link href="../AmazeUI-2.4.2/assets/css/admin.css" rel="stylesheet" type="text/css">#}
{#		<link href="../AmazeUI-2.4.2/assets/css/amazeui.css" rel="stylesheet" type="text/css">#}

{#		<link href="../css/personal.css" rel="stylesheet" type="text/css">#}
{#		<link href="../css/bilstyle.css" rel="stylesheet" type="text/css">#}

{#		<script src="../AmazeUI-2.4.2/assets/js/jquery.min.js" type="text/javascript"></script>#}
{#		<script src="../AmazeUI-2.4.2/assets/js/amazeui.js" type="text/javascript"></script>#}
{% endblock %}


{% block content %}
    <div class="am-cf am-padding">
						<div class="am-fl am-cf"><strong class="am-text-danger am-text-lg">账单明细</strong> / <small>Electronic&nbsp;bill</small></div>
					</div>
					<hr>

					<!--交易时间	-->

					<div class="order-time">
						<label class="form-label">交易时间：</label>
						<div class="show-input">
							<select class="am-selected" data-am-selected>
								<option value="today">今天</option>
								<option value="sevenDays" selected="">最近一周</option>
								<option value="oneMonth">最近一个月</option>
								<option value="threeMonths">最近三个月</option>
								<option class="date-trigger">全部交易</option>
							</select>
						</div>
                          <div class="clear"></div>
					</div>

					<table width="100%">

						<thead>
							<tr>
								<th class="memo"></th>
								<th class="time">创建时间</th>
								<th class="name">名称</th>
								<th class="amount">金额</th>
								<th class="action">操作</th>
							</tr>
						</thead>

						<tbody>
							<tr>
								<td class="img">
									<i><img src="{% static 'shop/images/songzi.jpg' %}"></i>
								</td>
								<td class="time">
									<p> 2016-01-28
									</p>
									<p class="text-muted"> 10:58
									</p>
								</td>
								<td class="title name">
									<p class="content">
										良品铺子精选松子，即开即食全国包邮
									</p>
								</td>

								<td class="amount">
									<span class="amount-pay">- 11.90</span>
								</td>
								<td class="operation">
									删除
								</td>
							</tr>

							<tr>

								<td class="img">
									<i><img src="{% static 'shop/images/songzi.jpg' %}"></i>
								</td>
								<td class="time">
									<p> 2016-01-28
									</p>
									<p class="text-muted"> 10:58
									</p>
								</td>
								<td class="title name">
									<p class="content">
										良品铺子精选松子，即开即食全国包邮
									</p>
								</td>

								<td class="amount">
									<span class="amount-pay">- 11.90</span>
								</td>
								<td class="operation">
									删除
								</td>
							</tr>
						</tbody>
					</table>
					<script type="text/javascript">
						$(document).ready(function() {
							$(".date-trigger").click(function() {
								$(".show-input").css("display", "none");
							});
						 })
					</script>

{% endblock %}

Retailers/templates/shop/person/bindphone.html
{% extends 'shop/frame.html' %}
{% load static %}
{% block title %}
    <title>绑定手机</title>
{% endblock %}
{% block head %}

    <link href="{% static 'shop/AmazeUI-2.4.2/assets/css/admin.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'shop/AmazeUI-2.4.2/assets/css/amazeui.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'shop/css/personal.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'shop/css/stepstyle.css' %}" rel="stylesheet" type="text/css"/>
    <script src="{% static 'shop/AmazeUI-2.4.2/assets/js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'shop/AmazeUI-2.4.2/assets/js/amazeui.js' %}" type="text/javascript"></script>


{% endblock %}


{% block content %}

    <div class="am-cf am-padding">
        <div class="am-fl am-cf"><strong class="am-text-danger am-text-lg">绑定手机</strong> /
            <small>Bind&nbsp;Phone</small>
        </div>
    </div>
    <hr/>
    <!--进度条-->
    <div class="m-progress">
        <div class="m-progress-list">
							<span class="step-1 step">
                                <em class="u-progress-stage-bg"></em>
                                <i class="u-stage-icon-inner">1<em class="bg"></em></i>
                                <p class="stage-name">绑定手机</p>
                            </span>
            <span class="step-2 step">
                                <em class="u-progress-stage-bg"></em>
                                <i class="u-stage-icon-inner">2<em class="bg"></em></i>
                                <p class="stage-name">完成</p>
                            </span>
            <span class="u-progress-placeholder"></span>
        </div>
        <div class="u-progress-bar total-steps-2">
            <div class="u-progress-bar-inner"></div>
        </div>
    </div>
    <form class="am-form am-form-horizontal">
        <div class="am-form-group bind">
            <label for="user-phone" class="am-form-label">验证手机</label>
            <div class="am-form-content">
                <span id="user-phone">{% if phone_number %}
                    {{ phone_number }}
                {% endif %}</span>
            </div>
        </div>
        <div class="am-form-group code">
            <label for="user-code" class="am-form-label">验证码</label>
            <div class="am-form-content">
                <input type="tel" id="user-code" placeholder="短信验证码">
            </div>
            <a class="btn" href="javascript:void(0);" onclick="sendMobileCode();" id="sendMobileCode">
                <div class="am-btn am-btn-danger" style="border-radius: 3px;">获取验证码</div>
            </a>
        </div>
        <div class="am-form-group">
            <label for="user-new-phone" class="am-form-label">验证手机</label>
            <div class="am-form-content">
                <input type="tel" id="user-new-phone" placeholder="绑定新手机号">
            </div>
        </div>
        <div class="am-form-group code">
            <label for="user-new-code" class="am-form-label" style="border-radius: 3px;">验证码</label>
            <div class="am-form-content">
                <input type="tel" id="user-new-code" placeholder="短信验证码">
            </div>
            <a class="btn" href="javascript:void(0);" onclick="sendMobileCode();" id="sendMobileCodee">
                <div class="am-btn am-btn-danger" style="border-radius: 3px;">获取验证码</div>
            </a>
        </div>
        <div class="info-btn">
            <div class="am-btn am-btn-danger" style="border-radius: 3px;" id="sumbit">保存修改</div>
            <p><span id='result'></span></p>
        </div>

    </form>
    <script src="http://apps.bdimg.com/libs/jquery/1.11.1/jquery.min.js"></script>
    <script>
        {# 获取验证码#}
        $(document).ready(function () {
            $("#sendMobileCode").click(function () {
                $.get("{% url 'goods:pswordcode_' %}", function (ret) {
                    $('#result').append(ret.data + '<br>');
                })
            });
            {# 获取新手机号验证码#}
            $("#sendMobileCodee").click(function () {
                var code = $('#user-code').val();
                var newphone = $('#user-new-phone').val();
                $.get("{% url 'goods:pswordcode_' %}", {
                    'code': code,
                    'newphone': newphone,
                }, function (ret) {
                    $('#result').append(ret.data + '<br>');
                })
            });

            {#提交数据#}

            $("#sumbit").click(function () {
                var code = $('#user-new-code').val();
                var newphone = $('#user-new-phone').val();
                $.get("{% url 'goods:bindphone' %}", {
                    'newphone': newphone,
                    'code': code
                }, function (ret) {
                    $('#result').append(ret.data + '<br>');
                    timename = setTimeout(window.location.href = "{% url 'goods:bindphone' %}", 2000);

                })
            });


        });

    </script>

{% endblock %}