Retailers/Goods/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from Goods import views

urlpatterns = [


    # 地址管理
    url(r'^address/$',views.address,name='address'),
    # 模板
    url(r'^frame/$',views.frame,name='frame'),
    # 账单
    url(r'^bill/$',views.bill,name='bill'),
    # 账单明细
    url(r'^billlist/$',views.billlist,name='billlist'),
    # 绑定手机
    url(r'^bindphone/$',views.bindphone,name='bindphone'),
    #新闻页面
    url(r'^blog/$',views.blog,name='blog'),
    #我的红包
    url(r'^bonus/$',views.bonus,name='bonus'),
    # 我的银行卡
    url(r'^cardlist/$', views.cardlist, name='cardlist'),
    # 银行卡绑定
    url(r'^cardmethod/$', views.cardmethod, name='cardmethod'),
    # 退换货管理
    url(r'^change/$', views.change, name='change'),
    # 我的收藏
    url(r'^collection/$', views.collection, name='collection'),
    # 评价管理
    url(r'^comment/$', views.comment, name='comment'),
    # 发表评论
    url(r'^commentlist/$', views.commentlist, name='commentlist'),
    url(r'^commentlist/(\d+)$', views.commentlist, name='commentlist1'),
    # 商品咨询
    url(r'^consultation/$', views.consultation, name='consultation'),
    # 优惠券
    url(r'^coupon/$', views.coupon, name='coupon'),
    # 邮箱验证
    url(r'^email/$', views.email, name='email'),
    # 我的足迹
    url(r'^foot/$', views.foot, name='foot'),
    # 实名认证
    url(r'^idcard/$', views.idcard, name='idcard'),
    # 个人中心
    url(r'^index/$', views.index, name='index'),
    # 个人资料
    url(r'^information/$', views.information, name='information'),
    # 物流信息
    url(r'^logistics/$', views.logistics, name='logistics'),
    # 我的消息
    url(r'^news/$', views.news, name='news'),
    # 订单管理
    url(r'^order/$', views.order, name='order'),
    # 订单详情
    url(r'^orderinfo/$', views.orderinfo, name='orderinfo'),
    url(r'^orderinfo/(\d+)$', views.orderinfo, name='orderinfo1'),
    # 修改密码
    url(r'^password/$', views.password, name='password'),
    # 我的积分
    url(r'^pointnew/$', views.pointnew, name='pointnew'),
    # 积分明细
    url(r'^points/$', views.points, name='points'),
    # 安全问题
    url(r'^question/$', views.question, name='question'),
    # 钱款去向
    url(r'^record/$', views.record, name='record'),
    # 退换货
    url(r'^refund/$', views.refund, name='refund'),
    url(r'^refund/(\d+)$', views.refund, name='refund1'),
    # 安全设置
    url(r'^safety/$', views.safety, name='safety'),
    # 支付密码
    url(r'^setpay/$', views.setpay, name='setpay'),
    # 意见反馈
    url(r'^suggest/$', views.suggest, name='suggest'),
    # 账户余额
    url(r'^wallet/$', views.wallet, name='wallet'),
    # 账户明细
    url(r'^walletlist/$', views.walletlist, name='walletlist'),
    # 登录页面
    url(r'^login/$', views.login, name='login'),
    # 获取注册验证码
    url(r'^auth_code_/$',views.auth_code_,name='auth_code_'),
    # 获取修改密码验证码
    url(r'^pswordcode_/$',views.pswordcode_,name='pswordcode_'),
    # 注册页面
    url(r'^register/$',views.register,name='register'),
    #删除session
    url(r'^sc/$',views.sc,name='sc'),
    #搜索路由
    url(r'^search/(\d+)/$',views.search,name='search1'),
    url(r'^search/$',views.search,name='search')

]

Retailers/Order/urls.py
from django.conf.urls import url, include
from Order import views

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^home/$', views.home,name='home'),
    url(r'^intro/(?P<goodid>\d+)/$',views.intro,name='intro'),
    # url(r'^purchase/$',views.purchase,name='purchase'),
    url(r'^price$',views.price_change,name='price'),
    url(r'^add_cart$',views.add_cart,name='add_cart'),
    url(r'^pay/(?P<commodityid>\d+)/(?P<count>\d+)/$',views.pay,name='pay'),
    url(r'^addre/$',views.addre,name='addre'),
    url(r'^express/$',views.express,name='express'),
    url(r'^commit/$',views.commit,name='commit'),
    url(r'^cart_commit/$', views.cart_commit, name='cart_commit'),
    url(r'^shopcart/$',views.shopcart,name='shopcart'),
    url(r'^check_cart$', views.check_cart, name='check_cart'),
    url(r'^delete_cart$', views.delete_cart, name='delete_cart'),
    url(r'^cart_pay/$', views.cart_pay, name='cart_pay'),
    url(r'^order_pay/$', views.order_pay, name='order_pay')
]

Retailers/Retailers/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),

    url(r'^goods/', include('Goods.urls', namespace='goods')),

    url(r'^order/', include('Order.urls', namespace='order')),

    url(r'^admin/', include('User.urls', namespace='admin'))
]

Retailers/User/urls.py
from django.conf.urls import url


from User import views
# from User.views import OrderPayView

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^add/$', views.add, name='add'),
    url(r'^login/$', views.login, name='login'),
    url(r'^index/$', views.index, name='index'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^productlist/(\d+)/$', views.productlist, name='productlist1'),
    url(r'^productlist/$', views.productlist, name='productlist'),
    url(r'^addgood/$', views.addgood, name='addgood'),
    url(r'^altergood/$', views.altergood, name='altergood'),
    url(r'^delgood/$', views.delgood, name='delgood'),
    url(r'^addband/$', views.addband, name='addband'),
    url(r'^alterband/$', views.alterband, name='alterband'),
    url(r'^delband/$', views.delband, name='delband'),
    url(r'^addbigcategory/$', views.addbigcategory, name='addbigcategory'),
    url(r'^alterbigcategory/$', views.alterbigcategory, name='alterbigcategory'),
    url(r'^delbigcategory/$', views.delbigcategory, name='delbigcategory'),
    url(r'^addsmallcategory/$', views.addsmallcategory, name='addsmallcategory'),
    url(r'^altersmallcategory/$', views.altersmallcategory, name='altersmallcategory'),
    url(r'^delsmallcategory/$', views.delsmallcategory, name='delsmallcategory'),
    url(r'^addattrbute/$', views.addattrbute, name='addattrbute'),
    url(r'^alterattrbute/$', views.alterattrbute, name='alterattrbute'),
    url(r'^delattrbute/$', views.delattrbute, name='delattrbute'),
    url(r'^addinventory/$', views.addinventory, name='addinventory'),
    url(r'^addinventory1/$', views.addinventory1, name='addinventory1'),
    url(r'^addinventory2/$', views.addinventory2, name='addinventory2'),
    url(r'^addinventory3/$', views.addinventory3, name='addinventory3'),
    url(r'^addinventory4/$', views.addinventory4, name='addinventory4'),
    url(r'^addgoodetail/$', views.addgoodetail, name='addgoodetail'),
    url(r'^orderlist/$', views.orderlist, name='orderlist'),
    url(r'^orderlist/(\d+)$', views.orderlist, name='orderlist1'),
    url(r'^choiceorder/(\d+)$', views.choiceorder, name='choiceorder1'),
    url(r'^choiceorder/$', views.choiceorder, name='choiceorder'),
    url(r'^delorder/(\d+)/$', views.delorder, name='delorder'),
    url(r'^orderdetail/(\d+)/$', views.orderdetail, name='orderdetail'),
    url(r'^sendorder/(\d+)/$', views.sendorder, name='sendorder'),
    url(r'^userlist/(\d+)/$', views.userlist, name='userlist1'),
    url(r'^userlist/$', views.userlist, name='userlist'),
    url(r'^deluser/(\d+)/$', views.deluser, name='deluser'),
    url(r'^userdetail/(\d+)/$', views.userdetail, name='userdetail'),
    url(r'^userrank/$', views.userrank, name='userrank'),
    url(r'^useraccount/$', views.useraccount, name='useraccount'),
    url(r'^setting/$', views.setting, name='setting'),
    url(r'^expresslist/$', views.expresslist, name='expresslist'),
    url(r'^delexpress/(\d)/$', views.delexpress, name='delexpress'),
    url(r'^paylist/$', views.paylist, name='paylist'),
    url(r'^delpayway/(\d)/$', views.delpayway, name='delpayway'),
    url(r'^pageviews/$', views.pageviews, name='pageviews'),
    url(r'^sales/$', views.sales, name='sales'),
    url(r"^pay/$", views.pay, name='pay'),
    url(r'^checkpay/$', views.checkpay, name='checkpay'),
    url(r'^test/$', views.test, name='test'),
    url(r'^turn/$', views.turn, name='turn')

]

Retailers/templates/shop/home/login.html
{% load static %}
<!DOCTYPE html>
<html>

<head lang="en">
    <meta charset="UTF-8">

    <title>登录</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="format-detection" content="telephone=no">
    <meta name="renderer" content="webkit">
    <meta http-equiv="Cache-Control" content="no-siteapp"/>

    <link rel="stylesheet" href="{% static 'shop/AmazeUI-2.4.2/assets/css/amazeui.css' %}"/>
    <link href="{% static 'shop/css/dlstyle.css' %}" rel="stylesheet" type="text/css">
</head>

<body>

<div class="login-boxtitle">
    <a href="home.html"><img alt="logo" src="{% static 'shop/images/logobig.png' %}"/></a>
</div>

<div class="login-banner">
    <div class="login-main">
        <div class="login-banner-bg"><span></span><img src="{% static 'shop/images/big.jpg' %}"/></div>
        <div class="login-box">

            <h3 class="title">登录商城</h3>

            <div class="clear"></div>

            <div class="login-form">
                <form action="{% url 'goods:login' %}" method="post">
                    {% csrf_token %}
                    <div class="user-name">
                        <label for="user"><i class="am-icon-user"></i></label>
                        <input type="text" name="user" id="user" placeholder="邮箱/手机/用户名">
                    </div>
                    <div class="user-pass">
                        <label for="password"><i class="am-icon-lock"></i></label>
                        <input type="password" name="password" id="password" placeholder="请输入密码">
                    </div>

            </div>

            <div class="login-links">
                <label for="remember-me"><input id="remember-me" type="checkbox">记住密码</label>
                <a href="#" class="am-fr">忘记密码</a>
                <a href="{% url 'goods:register'%}" class="zcnext am-fr am-btn-default">注册</a>
                <br/>
            </div>
            <div class="am-cf">
                <input type="submit" name="" value="登 录" class="am-btn am-btn-primary am-btn-sm">
            </div>
            </form>

            <div class="partner">
{#                <h3>合作账号</h3>#}
                <div class="am-btn-group">
                    {% if data %}
<li>{{ data }}</li>
                        {% else %}

                    {% endif %}

{#                    <li><a href="#"><i class="am-icon-weibo am-icon-sm"></i><span>微博登录</span> </a></li>#}
{#                    <li><a href="#"><i class="am-icon-weixin am-icon-sm"></i><span>微信登录</span> </a></li>#}
                </div>
            </div>

        </div>
    </div>
</div>


<div class="footer ">
    <div class="footer-hd ">
        <p>
            <a href="# ">恒望科技</a>
            <b>|</b>
            <a href="# ">商城首页</a>
            <b>|</b>
            <a href="# ">支付宝</a>
            <b>|</b>
            <a href="# ">物流</a>
        </p>
    </div>
    <div class="footer-bd ">
        <p>
            <a href="# ">关于恒望</a>
            <a href="# ">合作伙伴</a>
            <a href="# ">联系我们</a>
            <a href="# ">网站地图</a>
            <em>© 2015-2025 Hengwang.com 版权所有</em>
        </p>
    </div>
</div>
</body>

</html>

Retailers/templates/shop/home/shopcart.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">

		<title>购物车页面</title>

		<link href="{% static  '/shop/AmazeUI-2.4.2/assets/css/admin.css' %}" rel="stylesheet" type="text/css" />
		<link href="{% static  '/shop/basic/css/demo.css' %}" rel="stylesheet" type="text/css" />
		<link href="{% static  '/shop/css/cartstyle.css' %}" rel="stylesheet" type="text/css" />
		<link href="{% static  '/shop/css/optstyle.css' %}" rel="stylesheet" type="text/css" />

		<script type="text/javascript" src="{% static  '/shop/js/jquery.js' %}"></script>

	</head>

	<body>

		<!--顶部导航条 -->
		<div class="am-container header">
    <ul class="message-l">
        <div class="topMessage">
            <div class="menu-hd">
               {% if  'username' in request.session or 'email' in request.session or 'phone' in request.session  %}
                              欢迎
                                {% if request.session.username %}
                                    {{ request.session.username }}
                                {% elif request.session.email %}
                                    {{ request.session.email }}
                                {% elif request.session.phone %}
                                    {{ request.session.phone }}
                                {% endif %}
                                <a href="{% url 'goods:sc' %}" target="_top" class="h">退出</a>

                            {% else %}
                               <a href="{% url 'goods:login' %}" target="_top" class="h">亲，请登录</a>
                                <a href="{% url 'goods:register' %}" target="_top">免费注册</a>

                            {% endif %}

            </div>
        </div>
    </ul>
    <ul class="message-r">
        <div class="topMessage home">
            <div class="menu-hd"><a href="{% url 'order:home' %}" target="_top" class="h">商城首页</a></div>
        </div>
        <div class="topMessage my-shangcheng">
            <div class="menu-hd MyShangcheng"><a href="{% url 'goods:index' %}" target="_top"><i
                    class="am-icon-user am-icon-fw"></i>个人中心</a></div>
        </div>
        <div class="topMessage mini-cart">
            <div class="menu-hd"><a id="mc-menu-hd" href="{% url 'order:shopcart' %}" target="_top"><i
                    class="am-icon-shopping-cart  am-icon-fw"></i><span>购物车</span><strong id="J_MiniCartNum"
                                                                                          class="h level"><em>{{ shopnum }}</em></strong></a></div>
        </div>
        <div class="topMessage favorite">
            <div class="menu-hd"><a href="#" target="_top"><i class="am-icon-heart am-icon-fw"></i><span>收藏夹</span></a>
            </div>
        </div>
    </ul>
</div>

			<!--悬浮搜索框-->

            <div class="nav white">
                <div class="logoBig">
                    <li><img src="{% static 'shop/images/logobig.png' %}"/></li>
                </div>

                <div class="search-bar pr">
{#                    <a name="index_none_header_sysc" href="#"></a>#}
                    <form action="{% url 'goods:search' %}" method="post">
                        {% csrf_token %}
                        <input id="searchInput" name="index_none_header_sysc" type="text" placeholder="搜索" autocomplete="off">
                        <input id="ai-topsearch" class="submit am-btn" value="搜索" index="1" type="submit">
                    </form>
                </div>
            </div>

			<div class="clear"></div>

			<!--购物车 -->
			<div class="concent">
				<div id="cartTable">
					<div class="cart-table-th">
						<div class="wp">
							<div class="th th-chk">
								<div id="J_SelectAll1" class="select-all J_SelectAll">

								</div>
							</div>
							<div class="th th-item">
								<div class="td-inner">商品信息</div>
							</div>
							<div class="th th-price">
								<div class="td-inner">单价</div>
							</div>
							<div class="th th-amount">
								<div class="td-inner">数量</div>
							</div>
							<div class="th th-sum">
								<div class="td-inner">金额</div>
							</div>
							<div class="th th-op">
								<div class="td-inner">操作</div>
							</div>
						</div>
					</div>
					<div class="clear"></div>

					<tr class="item-list">
						<div class="bundle  bundle-last ">
							<div class="bundle-hd">
								<div class="bd-promos">
									<div class="bd-has-promo"><span class="bd-has-promo-content"></span>&nbsp;&nbsp;</div>
									<div class="act-promo">
										<a href="#" target="_blank"><span class="gt"></span></a>
									</div>
									<span class="list-change theme-login">编辑</span>
								</div>
							</div>
							<div class="clear"></div>
							<div class="bundle-main" id="mycart111">
                                {% for shop in myshop %}
                                    {% for commod in commodity %}
                                    {% if shop.cid == commod.id %}
                                    {% for good in goods %}
                                    {% if good.gid == commod.gid %}

                                    <input type="hidden" class="jilu" value="{{ shop.cid }}">
								    <ul class="item-content clearfix">
									<li class="td td-chk">
										<div class="cart-checkbox ">
                                            <input type="hidden" class="cid" value="{{ shop.cid }}">
											<input class="check" id="J_CheckBox_170037950254" name="items[]" value="170037950254" type="checkbox">

											<label for="J_CheckBox_170037950254"></label>
										</div>
									</li>
									<li class="td td-item">
										<div class="item-pic">
											<a href="/order/intro/{{ good.gid }}" target="_blank" data-title="{{ good.gname }}" class="J_MakePoint" data-point="tbcart.8.12">
												<img src="/static{{ good.picture }}" class="itempic J_ItemImg"></a>
										</div>
										<div class="item-info">
											<div class="item-basic-info">
												<a href="#" target="_blank" title="{{ good.gname }}" class="item-title J_MakePoint" data-point="tbcart.8.11">{{ good.gname }}</a>
											</div>
										</div>
									</li>
									<li class="td td-info">
										<div class="item-props item-props-can">
											<span class="sku-line">口味：{{ commod.smallclassesattribute }}</span>
                                            {% for no in norm %}
                                                {% if commod.specification_id == no.id %}
											<span class="sku-line">包装：{{ no.specification }}</span>
                                                {% endif %}
                                            {% endfor %}
{#											<span tabindex="0" class="btn-edit-sku theme-login">修改</span>#}
											<i class="theme-login am-icon-sort-desc"></i>
										</div>
									</li>
									<li class="td td-price">
										<div class="item-price price-promo-promo">
											<div class="price-content">
												<div class="price-line">
													<em class="price-original">{{ commod.historicalprices }}</em>
												</div>
												<div class="price-line">
													<em class="J_Price price-now show_price" tabindex="0">￥<b>{{ commod.price }}</b></em>
												</div>
											</div>
										</div>
									</li>
									<li class="td td-amount">
										<div class="amount-wrapper ">
											<div class="item-amount ">
												<div class="sl">
													<input class="min am-btn" name="" type="button" value="-" />
													<input class="text_box" name="" type="text" value="{{ shop.goodscount }}" style="width:30px;" />
													<input class="add am-btn" name="" type="button" value="+" />
												</div>
											</div>
										</div>
									</li>
									<li class="td td-sum">
										<div class="td-inner">
											<em tabindex="0" class="J_ItemSum number total"><em>{{ shop.totalprice }}</em></em>
										</div>
									</li>
									<li class="td td-op">
										<div class="td-inner">
											<a title="移入收藏夹" class="btn-fav" href="#">
                  移入收藏夹</a>
											<a href="javascript:;" data-point-url="#" -onclick="mydelete()" class="delete mydelete">
                  删除</a>
										</div>
									</li>
								</ul>
                                        {% endif %}
                                        {% endfor %}
                                        {% endif %}
								{% endfor %}
								{% endfor %}
								
								

													
								
								
								
							</div>
						</div>
					</tr>
					<div class="clear"></div>

					<tr class="item-list">

					</tr>
				</div>
				<div class="clear"></div>

				<div class="float-bar-wrapper">
					<div id="J_SelectAll2" class="select-all J_SelectAll">
						<div class="cart-checkbox">
							<input class="check-all check" id="J_SelectAllCbx2" name="select-all" value="true" type="checkbox">
							<label for="J_SelectAllCbx2"></label>
						</div>
						<span>全选</span>
					</div>
					<div class="operations">
						<a href="#" hidefocus="true" class="deleteAll"  >删除</a>
						<a href="#" hidefocus="true" class="J_BatchFav">移入收藏夹</a>
					</div>
					<div class="float-bar-right">
						<div class="amount-sum">
							<span class="txt">已选商品</span>
							<em id="J_SelectedItemsCount">{{ shuliang }}</em><span class="txt">件</span>
							<div class="arrow-box">
								<span class="selected-items-arrow"></span>
								<span class="arrow"></span>
							</div>
						</div>
						<div class="price-sum">
							<span class="txt">合计:</span>
							<strong class="price">¥<em id="J_Total">{{ heji }}</em></strong>
						</div>
						<div class="btn-area">
							<a href="{% url 'order:order_pay' %}" id="J_Go" class="submit-btn submit-btn-disabled" onclick="jiesuan()" aria-label="请注意如果没有选择宝贝，将无法结算">
								<span>结&nbsp;算</span></a>
						</div>
					</div>

				</div>

				<div class="footer">
					<div class="footer-hd">
						<p>
							<a href="#">恒望科技</a>
							<b>|</b>
							<a href="#">商城首页</a>
							<b>|</b>
							<a href="#">支付宝</a>
							<b>|</b>
							<a href="#">物流</a>
						</p>
					</div>
					<div class="footer-bd">
						<p>
							<a href="#">关于恒望</a>
							<a href="#">合作伙伴</a>
							<a href="#">联系我们</a>
							<a href="#">网站地图</a>
							<em>© 2015-2025 Hengwang.com 版权所有</em>
						</p>
					</div>
				</div>

			</div>

			<!--操作页面-->

			<div class="theme-popover-mask"></div>

			<div class="theme-popover">
				<div class="theme-span"></div>
				<div class="theme-poptit h-title">
					<a href="javascript:;" title="关闭" class="close">×</a>
				</div>
				<div class="theme-popbod dform">
					<form class="theme-signin" name="loginform" action="" method="post">

						<div class="theme-signin-left">

							<li class="theme-options">
								<div class="cart-title">颜色：</div>
								<ul>
									<li class="sku-line selected">12#川南玛瑙<i></i></li>
									<li class="sku-line">10#蜜橘色+17#樱花粉<i></i></li>
								</ul>
							</li>
							<li class="theme-options">
								<div class="cart-title">包装：</div>
								<ul>
									<li class="sku-line selected">包装：裸装<i></i></li>
									<li class="sku-line">两支手袋装（送彩带）<i></i></li>
								</ul>
							</li>
							<div class="theme-options">
								<div class="cart-title number">数量</div>
								<dd>
									<input class="min am-btn am-btn-default" name="" type="button" value="-" />
									<input class="text_box" name="" type="text" value="1" style="width:30px;" />
									<input class="add am-btn am-btn-default" name="" type="button" value="+" />
									<span  class="tb-hidden">库存<span class="stock">1000</span>件</span>
								</dd>

							</div>
							<div class="clear"></div>
							<div class="btn-op">
								<div class="btn am-btn am-btn-warning">确认</div>
								<div class="btn close am-btn am-btn-warning">取消</div>
							</div>

						</div>
						<div class="theme-signin-right">
							<div class="img-info">
								<img src="/static/shop/images/kouhong.jpg_80x80.jpg" />
							</div>
							<div class="text-info">
								<span class="J_Price price-now">¥39.00</span>
								<span id="Stock" class="tb-hidden">库存<span class="stock">1000</span>件</span>
							</div>
						</div>

					</form>
				</div>
			</div>
		<!--引导 -->
		<div class="navCir">
			<li><a href="{% url 'order:home' %}"><i class="am-icon-home "></i>首页</a></li>
			<li><a href="sort.html"><i class="am-icon-list"></i>分类</a></li>
			<li class="active"><a href="shopcart.html"><i class="am-icon-shopping-basket"></i>购物车</a></li>	
			<li><a href="../person/index.html"><i class="am-icon-user"></i>我的</a></li>					
		</div>
	</body>

</html>

Retailers/templates/shop/home/success.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
<title>付款成功页面</title>
<link rel="stylesheet"  type="text/css" href="../AmazeUI-2.4.2/assets/css/amazeui.css"/>
<link href="../AmazeUI-2.4.2/assets/css/admin.css" rel="stylesheet" type="text/css">
<link href="../basic/css/demo.css" rel="stylesheet" type="text/css" />

<link href="../css/sustyle.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="../basic/js/jquery-1.7.min.js"></script>

</head>

<body>


<!--顶部导航条 -->
<div class="am-container header">
  <ul class="message-l">
    <div class="topMessage">
     <div class="menu-hd">
       <a href="#" target="_top" class="h">亲，请登录</a>
       <a href="#" target="_top">免费注册</a>
     </div></div>
  </ul>
  <ul class="message-r">
    <div class="topMessage home"><div class="menu-hd"><a href="#" target="_top" class="h">商城首页</a></div></div>
    <div class="topMessage my-shangcheng"><div class="menu-hd MyShangcheng"><a href="#" target="_top"><i class="am-icon-user am-icon-fw"></i>个人中心</a></div></div>
    <div class="topMessage mini-cart"><div class="menu-hd"><a id="mc-menu-hd" href="#" target="_top"><i class="am-icon-shopping-cart  am-icon-fw"></i><span>购物车</span><strong id="J_MiniCartNum" class="h">0</strong></a></div></div>
    <div class="topMessage favorite"><div class="menu-hd"><a href="#" target="_top"><i class="am-icon-heart am-icon-fw"></i><span>收藏夹</span></a></div>
  </ul>
</div>

<!--悬浮搜索框-->

<div class="nav white">
	<div class="logo"><img src="../images/logo.png" /></div>
    <div class="logoBig">
      <li><img src="../images/logobig.png" /></li>
    </div>
    
    <div class="search-bar pr">
        <a name="index_none_header_sysc" href="#"></a>       
        <form>
        <input id="searchInput" name="index_none_header_sysc" type="text" placeholder="搜索" autocomplete="off">
        <input id="ai-topsearch" class="submit" value="搜索" index="1" type="submit"></form>
    </div>     
</div>

<div class="clear"></div>



<div class="take-delivery">
 <div class="status">
   <h2>您已成功付款</h2>
   <div class="successInfo">
     <ul>
       <li>付款金额<em>¥9.90</em></li>
       <div class="user-info">
         <p>收货人：艾迪</p>
         <p>联系电话：15871145629</p>
         <p>收货地址：湖北省 武汉市 武昌区 东湖路75号众环大厦</p>
       </div>
             请认真核对您的收货信息，如有错误请联系客服
                               
     </ul>
     <div class="option">
       <span class="info">您可以</span>
        <a href="../person/order.html" class="J_MakePoint">查看<span>已买到的宝贝</span></a>
        <a href="../person/orderinfo.html" class="J_MakePoint">查看<span>交易详情</span></a>
     </div>
    </div>
  </div>
</div>


<div class="footer" >
 <div class="footer-hd">
 <p>
 <a href="#">恒望科技</a>
 <b>|</b>
 <a href="#">商城首页</a>
 <b>|</b>
 <a href="#">支付宝</a>
 <b>|</b>
 <a href="#">物流</a>
 </p>
 </div>
 <div class="footer-bd">
 <p>
 <a href="#">关于恒望</a>
 <a href="#">合作伙伴</a>
 <a href="#">联系我们</a>
 <a href="#">网站地图</a>
 <em>© 2015-2025 Hengwang.com 版权所有</em>
 </p>
 </div>
</div>


</body>
</html>